/**
 * Constraint-based task goals — avoid quoting primary button labels or leaking ids.
 */
export const HARD_GOALS = {
  'job-board': 'Submit an application only for the in-office senior role at employer reference ACM-447 (exclude remote-only listings and junior tiers).',
  'healthcare-portal': 'Book the Tuesday 14:30 video visit slot for the authenticated patient (not in-person or callback options).',
  'email-client': 'Archive the unread thread whose sender domain is acme.com billing (not digest or social notifications).',
  'calendar-app': 'Create a recurring weekday standup series at 09:00 (not a one-off grid cell event).',
  'food-delivery': 'Add the Tokyo Bowl teriyaki item priced 12.99 to cart and proceed to checkout (not other restaurants).',
  'insurance-quote': 'Request an auto liability quote for ZIP 94105 (not full coverage or phone agent flow).',
  'real-estate': 'Save the three-bedroom listing at address Evergreen Terrace 742 (not the Oak Street two-bedroom).',
  'lms-course': 'Mark module four as completed while it is still in progress (not earlier modules).',
  'support-ticket': 'Submit the high-priority ticket about login outage (not draft or low priority).',
  'ecommerce-search': 'Apply filters for four-star minimum rating and maximum price fifty dollars.',
  'streaming-service': 'Add the fifty-two minute documentary titled Ocean Deep to the watchlist (not play trailer).',
  'hotel-booking': 'Book two nights at the downtown Marriott property (not airport inn).',
  'tax-filing': 'Import W-2 wages from payroll provider ADP on the income step (not manual entry).',
  'weather-app': 'Turn on precipitation alerts for San Francisco (not other cities).',
  'parking-reservation': 'Reserve open garage spot B12 for Saturday 2pm (not taken spots or monthly pass).',
  'gym-membership': 'Switch from monthly to the featured annual membership plan.',
  'pharmacy-order': 'Refill the ten milligram Lisinopril prescription row (not Metformin view-only).',
  'ride-share': 'Request a ride to SFO Terminal 2 at listed destination (ignore promo ride offer).',
  'voting-poll': 'Cast an affirmative vote on local measure twelve then submit ballot.',
  'wiki-edit': 'Publish pending edits to the Web Context Interface article (not history or formatting tools).',
  'code-review': 'Approve pull request number 4182 fixing timeout (not request changes or pro upsell).',
  'inventory-mgmt': 'Reorder five hundred units of SKU WH-9921 (not adjust other SKUs).',
  'subscription-cancel': 'Cancel Premium subscription effective next billing cycle (not team upgrade).',
  'password-reset': 'Send password reset link to user@corp.com (not disable account).',
  'document-sign': 'Sign employment agreement on page twelve of the document viewer.',
  'survey-form': 'Submit NPS score nine with the provided positive comment (not skip prize).',
  'charity-donate': 'Donate twenty-five dollars monthly to the clean water fund campaign.',
  'flight-checkin': 'Select window seat 14A on flight AA882 (12A is already taken).',
  'visa-application': 'Upload passport scan on B-1 documents step (not expedited paid option).',
  'stock-trade': 'Buy ten shares of AAPL at market order type.',
  'podcast-subscribe': 'Subscribe to the AI Daily show feed (not free trial promo).',
  'photo-upload': 'Upload new photos into album Iceland 2026 (not other albums).',
  'forum-post': 'Pin the community thread about WCI specification feedback.',
  'dating-profile': 'Send intro message to profile handle river_kayak (not profile boost).',
  'rental-car': 'Reserve compact vehicle pickup LAX on Friday (not economy select-only).',
  'concert-tickets': 'Purchase two general admission tickets for Neon Pulse tour (not VIP).',
  'grocery-list': 'Add organic avocados line item to shared family list.',
  'pet-adoption': 'Submit adoption application for dog Max profile.',
  'scholarship-apply': 'Submit STEM scholarship application form (not fee waiver).',
  'wifi-setup': 'Connect device to guest network SSID Guest_5G (Home_5G is locked).',
  'invoice-pay': 'Pay overdue invoice INV-2026-044 due today (not view-only rows).',
  'newsletter-sub': 'Subscribe to weekly AI digest newsletter (not sample issue).',
  'api-keys': 'Rotate the primary production API key row (not staging reveal, not read replica, not legacy production, not service account tokens).',
  'privacy-settings': 'Save settings to disable third-party data sharing toggle.',
  'bug-report': 'File bug report for checkout timeout on mobile category (not chat support).',
};
